# needed to work around https://github.com/travis-ci/travis-ci/issues/9713
sudo: true

language: scala

addons:
  hosts:
    - myshorthost
  hostname: myshorthost
  apt:
    packages:
      - graphviz

env:
  global:
    # PGP_PASSPHRASE
    - secure: "SkBtn/6OjEldoikn0MFuyeLT/pau27kwKSDYTVQeJ4BKDzdWLwLE5Q3RukLGttIfNdhOvRoocpQSW9GkZfibTHmwrRnAokucfZCqTsKbwoOp1xIoOh5GrrVrB6gcP7WBTKinqFdBgSvLOrP7GviImz4ZuB9wq1r+mToGG4pDrXc="
    # SONA_USER
    - secure: "JSv/Er6q1XtTpRH1bpU63YBf7ufwg0vW+Kv/udQBtr8YX/P3gRYC1x6hW4uwftaKMYh7wXDkfNy51SRpH3kUptdJvjPUifVElyPiYlsumetmD+rZJmxX6agx+U5pdjIXPqPoton9MdSVHNTROeTu339bDak0Z+N5ht5wRfjP7F4="
    # SONA_PASS
    - secure: "OIVtcj7AHZr8Grpf03ZmZsygcADewiYIvSnRwLYCx+5AqOzs39EZ68DsIOxi7wEXVUbVj5RvLXpKzLX3iN+UszLOQRoFPFQyyn+3Y50f8T2aRxdZtInzXn0sCVTj4Hhd/zbKl1W+2Nh3Sqazab7tFoQVzEyYqhcPeiNRMF7h+aY="

script:
  - echo $JAVA_HOME
  # work around https://github.com/travis-ci/travis-ci/issues/9713
  - if [[ $JAVA_HOME = *java-6* ]]; then jdk_switcher use openjdk6; fi
  - java -version
  - admin/build.sh

addons:
  apt:
    packages:
      - openjdk-6-jdk

jdk:
  - openjdk6
  - oraclejdk8
  - oraclejdk9

notifications:
  email:
    - adriaan.moors@lightbend.com
    - antoine@gourlay.fr

before_cache:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" | xargs rm
cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/boot
  - $HOME/.sbt/launchers
