sudo: required

language: scala
jdk:
  - oraclejdk8
  - openjdk11

scala:
  - 2.11.12
  - 2.12.8
  - 2.13.0-RC1

env:
  global:
    # PGP_PASSPHRASE
    - secure: "SkBtn/6OjEldoikn0MFuyeLT/pau27kwKSDYTVQeJ4BKDzdWLwLE5Q3RukLGttIfNdhOvRoocpQSW9GkZfibTHmwrRnAokucfZCqTsKbwoOp1xIoOh5GrrVrB6gcP7WBTKinqFdBgSvLOrP7GviImz4ZuB9wq1r+mToGG4pDrXc="
    # SONA_USER
    - secure: "DRoNJ0TNlccqEQ761m5ta/+cesErkcgiwxw0n+IPZMofh1N2IVvhB6hC2mzjy/6iqNE97176L/jIc9nrHunYlpMMMhhD8+3k2UfCUULxpR2zXj6AW2+d38DPlirUy8HDYhonvMhxKEStlv55zDbOIadKsXnFoG7w9CxGZd2AJhE="
    # SONA_PASS
    - secure: "C2Y8a080/qum7YwfZBL6acvduv6j7m0acF4TECYSTJTj62miQ69ygfBS4/JlEXXr+lFPL3mrtexoGSA/DSvo8FoMM6rtypTxtsyLND2dxlwS+U3q3qKxH0BUCUy7WpTzAO4NzZ0B0avR+kRtsWjwpSx7WhXQSh1K8z7WDC49Tbk="
  matrix:
    # The empty SCALAJS_VERSION will only compile for the JVM
    - SCALAJS_VERSION=
    - SCALAJS_VERSION=0.6.27
    - SCALAJS_VERSION=1.0.0-M7

script: admin/build.sh

notifications:
  email:
    - adriaan.moors@lightbend.com
    - seth.tisue@lightbend.com
    - antoine@gourlay.fr

before_cache:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" | xargs rm
cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/boot
  - $HOME/.sbt/launchers
