dist: trusty
language: scala
jdk:
  - oraclejdk8
  - openjdk11

scala:
  - 2.11.12
  - 2.12.8
  - 2.13.0-RC2

env:
  global:
    # PGP_PASSPHRASE
    - secure: "SkBtn/6OjEldoikn0MFuyeLT/pau27kwKSDYTVQeJ4BKDzdWLwLE5Q3RukLGttIfNdhOvRoocpQSW9GkZfibTHmwrRnAokucfZCqTsKbwoOp1xIoOh5GrrVrB6gcP7WBTKinqFdBgSvLOrP7GviImz4ZuB9wq1r+mToGG4pDrXc="
    # SONA_USER
    - secure: "JSv/Er6q1XtTpRH1bpU63YBf7ufwg0vW+Kv/udQBtr8YX/P3gRYC1x6hW4uwftaKMYh7wXDkfNy51SRpH3kUptdJvjPUifVElyPiYlsumetmD+rZJmxX6agx+U5pdjIXPqPoton9MdSVHNTROeTu339bDak0Z+N5ht5wRfjP7F4="
    # SONA_PASS
    - secure: "OIVtcj7AHZr8Grpf03ZmZsygcADewiYIvSnRwLYCx+5AqOzs39EZ68DsIOxi7wEXVUbVj5RvLXpKzLX3iN+UszLOQRoFPFQyyn+3Y50f8T2aRxdZtInzXn0sCVTj4Hhd/zbKl1W+2Nh3Sqazab7tFoQVzEyYqhcPeiNRMF7h+aY="
  matrix:
    # The empty SCALAJS_VERSION will only compile for the JVM
    - SCALAJS_VERSION=
    - SCALAJS_VERSION=0.6.28
    - SCALAJS_VERSION=1.0.0-M8

matrix:
  include:
    - env: SCALANATIVE_VERSION=0.3.8
      jdk: oraclejdk8

script: admin/build.sh

notifications:
  email:
    - adriaan.moors@lightbend.com
    - seth.tisue@lightbend.com
    - antoine@gourlay.fr

before_cache:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" | xargs rm
cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/boot
  - $HOME/.sbt/launchers
